<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>


<!--############# NOVO MENU ############################### -->

<style>

  .topmenubar{
  border-bottom: 5px solid #58007e;
}

  .novidadesbar{
  border-bottom: 5px solid #ffee30;
}

  .promocoesbar{
  border-bottom: 5px solid #f12c2c;
}

  .juiceimportadobar{
  border-bottom: 5px solid #327b9e;
}

  .saltnicimportadobar{
  border-bottom: 5px solid #499324;
}

  .juicenacionalbar{
  border-bottom: 5px solid #00a787;
}

  .saltnicnacionalbar{
  border-bottom: 5px solid #9cb300;
}

  .hardwarebar{
  border-bottom: 5px solid #3b00a3;
}

  .coilsbar{
  border-bottom: 5px solid #a50097;
}

  .acessoriosbar{
  border-bottom: 5px solid #265c0b;
}



    .button{
      background-image: linear-gradient( to right, #33FFBB , #3396FF , #33CAFF , #33FFD1 );
      width: 90px;
      height: 40px;
    }

    /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}

/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}


.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 1160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}

.menuContainerFloat{
  float: left;  
  /*border-style: solid;
  border-color: blue;*/
  width: 100%;
  color: white;
  font-size: x-small;

}

.commonMenu{
  margin-left: 30px;
  float: left;
  bottom: 0px;
}
</style>



<div class="menuContainerFloat">
  <!--
<img src="https://cdn.jsdelivr.net/gh/paulosergioduff/cdnfiles@master/images/logo-white-cloud.png">
  -->
<span >
    <a
        class="logo"
        href="<?= $block->escapeUrl($block->getUrl('')) ?>"
        title="<?= $block->escapeHtmlAttr($storeName) ?>"
        aria-label="store logo">
        <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
             title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
        />
    </a>
</span>

  <span class="topmenubar
   dropdown commonMenu ">TOP 20

 <div class="dropdown-content">
    <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")->setDisplayType("all_products")->setProductsCount("5")->setTemplate("product/widget/new/content/new_grid.phtml")->toHtml(); ?>

  </div>

</span>

  <span class="novidadesbar
   dropdown commonMenu ">NOVIDADES



</span>

  <span class="promocoesbar
   dropdown commonMenu ">PROMOÇÕES



</span>

  <span class="juiceimportadobar
   dropdown commonMenu ">JUICE IMPORTADO



</span>

  <span class="saltnicimportadobar
   dropdown commonMenu ">SALTNIC IMPORTADO



</span>

  <span class="juicenacionalbar
   dropdown commonMenu ">JUICE NACIONAL



</span>

  <span class="saltnicnacionalbar
   dropdown commonMenu ">SALTNIC NACIONAL



</span>

  <span class="hardwarebar
   dropdown commonMenu ">HARDWARE



</span>


  <span class="coilsbar
   dropdown commonMenu ">COILS



</span>


  <span class="acessoriosbar
   dropdown commonMenu ">ACESSÓRIOS



</span>


<!--################ FIM DO NOVO MENU ######################### -->
