<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \StudioEmma\Optimus\Block\Html\Topmenu
 */
?>
<?php
    $columnsLimit = $block->getColumnsLimit() ?: 0;
    $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
    $currentUrl = $block->getCurrentUrl();
?>

<nav class="navigation" data-action="navigation" style="background-color: rgba(0,0,0,0.0);">





	<!-- menu original -->
    <!--<ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 home <?php if($currentUrl == '/'): ?>active<?php endif; ?>"><a href="/" title="<?php echo __('Home') ?>" class="level-top"><span></span></a></li>
        <?php echo $_menu; ?>
    </ul>-->
</nav>

<!-- MODAL DO SITE -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                                          <img id="Image-Maps-Com-image-maps-2020-09-07-165456" src="https://www.image-maps.com/m/private/0/39o1s8imvisapk04ogastq1mga_modal-maio-idade.png" border="0" width="697" height="423" orgWidth="697" orgHeight="423" usemap="#image-maps-2020-09-07-165456" alt="" / style="border-style: solid; border-color: red;">
<map name="image-maps-2020-09-07-165456" id="ImageMapsCom-image-maps-2020-09-07-165456">
<area  alt="" title="" href="javascript: maiorDeIdade();" shape="rect" coords="131,316,328,369" style="outline:none;" target="_self"     />
<area  alt="" title="" href="javascript: menorDeIdade();" shape="rect" coords="340,315,537,368" style="outline:none;" target="_self"     />
<area shape="rect" coords="695,421,697,423" alt="Image Map" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
</map>
            </div>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		
		<?php
			$situacao_usuario = "pendente";
			if($situacao_usuario == "pendente"){ ?>
				<script>
					$(document).ready(function(){
						$('#myModal').modal('show');
					});
				</script>
			<?php } ?>

            <script type="text/javascript">
                function maiorDeIdade(){
                    alert('maior de idade');
                }

                function menorDeIdade(){
                    alert('menor de idade');
                }
            </script>



<!-- MODAL DO SITE -->
